name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          

          # Options
          # user: mateusfg7
          template: classic
          
          config_display: large
          config_timezone: America/Sao_Paulo
          config_animations: yes
          
          base: header, activity, repositories, metadata
          base_indepth: yes
          # repositories_forks: yes
          repositories: 60
          repositories_affiliations: owner, collaborator
          commits_authoring: Mateus Felipe Gonçalves, Mateus Felipe, mateusfg7, mateusfg7@users.noreply.github.com
          
          plugin_lines: yes
          plugin_lines_history_limit: 3
          
          plugin_languages: yes
          plugin_languages_ignored: scss, css, html, qml, perl
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_details: lines
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: no
          
          # plugin_topics: yes
          # plugin_topics_limit: 20
          # plugin_topics_mode: icons
          # plugin_topics_sort: starred
          
          plugin_code: yes
          plugin_code_lines: 6
